---
title: Smartless - Willem Dafoe
date: 2023-09-07
categories:
  - podcast
---

On one of my long drives recently, I was listening to the [Smartless episode](https://www.smartless.com/episodes/episode/22b8d8d5/willem-dafoe) featuring [Willem Dafoe](https://en.wikipedia.org/wiki/Willem_Dafoe).

He shared a perspective that resonated with me. Although he's American, he lives in Italy, making him an immigrant there. He mentioned that being an immigrant is a liberating experience for him, allowing him to see things from a distance, with an outsider's perspective.

I'd never considered it, but it rings true for me as well.
Being an immigrant in America, I have the unique vantage point to observe the absurdities, joys, and sorrows of this place, but from a distance.
Having lived in another country gives me a completely different perspective, knowing how things could be elsewhere.
I can never become too myopic here, as I never get too close to things.
There is a sad yet liberating quality to it.




