---
title: History-of-Math Resources
categories:
  - resources
  - history of math
date: 2023-08-21 22:30:11
---

I've always been fascinated by the history of mathematics. Some of the classic and dramatic discoveries I read a kid were those of non-Euclidean geometry, Galois theory, the proof of Fermat’s last theorem, as well as Cantor and Gödel’s breakthroughs in logic. However, some of the more commonplace achievements, such as the invention of calculus by Newton and its subsequent formalization a century later through $\epsilon \delta$ proofs, also possess a very intriguing narrative that involves not only mathematicians but also philosophers and theologians[^1].

I was pleasantly surprised to come across the following resources for learning mathematical concepts through historical sources:

- [https://www.cs.nmsu.edu/historical-projects/projects.php](https://www.cs.nmsu.edu/historical-projects/projects.php
)
- [https://digitalcommons.ursinus.edu/triumphs/](https://digitalcommons.ursinus.edu/triumphs/)

Apparently, these resources are part of an NSF-funded project *Transforming Instruction In Undergraduate Mathematics Via Primary Historical Sources* [TRIUMPHS](https://blogs.ursinus.edu/triumphs/).  I hope I find the time to read through with these materials.

[^1]: [Who Gave You the Epsilon? Cauchy and the Origins of Rigorous Calculus Judith V. Grabiner](https://www.jstor.org/stable/2975545)
